[project]
name = "cloudwatch-logs-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
# Dependencies are now defined in main.py using UV inline script
